### PR TITLE
Modernise darts python code & Makefile fixes

### PR DESCRIPTION
**Pull request by dipietrantonio**
Python code for darts mixed tabs and spaces which is not possible anymore. Replaced use of numpy.random with the Python random module. Increased number of trials because sometimes the test failed.

- Fixes Makefile variables

### CODE REVIEW

**Comment by dipietrantonio** [comment]
In the Makefiles I have removed flags to link openmp, as they differ based on the compiler to be used. This makes the code compatible with reframe too, where these flags are set during tests execution. What could be an alternative approach?
@marcodelapierre @ddeeptimahanti

**Comment by marcodelapierre** [comment]
apparently you can do tests in makefiles (never done it myself):
https://stackoverflow.com/questions/24563150/makefile-with-os-dependent-compiler#24563202

for Pawsey,
on non-Crays, you might use the COMPILER env variable as a test; 
on Crays, it looks like the variable PE_ENV (from the modules PrgEnv-) may be helpful.

for more portable solutions, I am not sure..

**Comment by dipietrantonio** [comment]
Hi Marco,

I have modified the makefiles to set openmp flags according to the compiler used.

**Comment by marcodelapierre** [comment]
Thanks Cristian.

Just one thing, Crays and non Crays differ in wrappers and so on.
Now, I can't recall on which systems these examples are typically run...if only on one, just ensure that the syntax works on that relevant one.

Thanks again!

**Comment by dipietrantonio** [comment]
Closing as we will probably come up with new examples.

**Pull request closed without merging**
